spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

app:
  rabbitmq:
    exchange: device.locations.exchange
    queue: device.locations.queue
    routing-key: device.location.received
    dlx: device.locations.dlx
    dlq: device.locations.dlq
    dlq-routing-key: device.location.received.dlq
